# Form implementation generated from reading ui file '.\main.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1140, 837)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame_CentralAjuda = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_CentralAjuda.setGeometry(QtCore.QRect(870, 190, 231, 291))
        self.frame_CentralAjuda.setStyleSheet("QFrame{\n"
"\n"
"    border-radius:10px;\n"
"    background-color: #efefef;\n"
"border:0px;\n"
"\n"
"\n"
"}")
        self.frame_CentralAjuda.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_CentralAjuda.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_CentralAjuda.setObjectName("frame_CentralAjuda")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.frame_CentralAjuda)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.label_TitleCentralAjuda = QtWidgets.QLabel(parent=self.frame_CentralAjuda)
        self.label_TitleCentralAjuda.setMaximumSize(QtCore.QSize(16777215, 50))
        self.label_TitleCentralAjuda.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.label_TitleCentralAjuda.setStyleSheet("QLabel{\n"
"text-align:center;\n"
"color:#010101;\n"
"border:0px;\n"
"font-size:30px;\n"
"font-weight: bold;\n"
"\n"
"}")
        self.label_TitleCentralAjuda.setTextFormat(QtCore.Qt.TextFormat.PlainText)
        self.label_TitleCentralAjuda.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_TitleCentralAjuda.setObjectName("label_TitleCentralAjuda")
        self.verticalLayout_20.addWidget(self.label_TitleCentralAjuda)
        self.pushButton_BtnAjuda01 = QtWidgets.QPushButton(parent=self.frame_CentralAjuda)
        self.pushButton_BtnAjuda01.setMinimumSize(QtCore.QSize(0, 65))
        self.pushButton_BtnAjuda01.setMaximumSize(QtCore.QSize(16777215, 65))
        self.pushButton_BtnAjuda01.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton_BtnAjuda01.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.pushButton_BtnAjuda01.setStyleSheet("QPushButton{\n"
"    text-align:left;\n"
"    color:#585858;\n"
"\n"
"    font-size:20px;\n"
"    cursor: pointer;\n"
"\n"
"    background-color:transparent;\n"
"    border-radius:0px;\n"
"    border-bottom: 1px solid #acacbf;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color:#4b6272;\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/img/+-15.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_BtnAjuda01.setIcon(icon)
        self.pushButton_BtnAjuda01.setIconSize(QtCore.QSize(150, 150))
        self.pushButton_BtnAjuda01.setObjectName("pushButton_BtnAjuda01")
        self.verticalLayout_20.addWidget(self.pushButton_BtnAjuda01)
        self.pushButton_BtnAjuda04 = QtWidgets.QPushButton(parent=self.frame_CentralAjuda)
        self.pushButton_BtnAjuda04.setMinimumSize(QtCore.QSize(0, 65))
        self.pushButton_BtnAjuda04.setMaximumSize(QtCore.QSize(16777215, 65))
        self.pushButton_BtnAjuda04.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton_BtnAjuda04.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.pushButton_BtnAjuda04.setStyleSheet("QPushButton{\n"
"    text-align:left;\n"
"    color:#585858;\n"
"\n"
"    font-size:20px;\n"
"    cursor: pointer;\n"
"\n"
"    background-color:transparent;\n"
"    border-radius:0px;\n"
"    border-bottom: 1px solid #acacbf;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color:#4b6272;\n"
"}")
        self.pushButton_BtnAjuda04.setIcon(icon)
        self.pushButton_BtnAjuda04.setIconSize(QtCore.QSize(150, 150))
        self.pushButton_BtnAjuda04.setObjectName("pushButton_BtnAjuda04")
        self.verticalLayout_20.addWidget(self.pushButton_BtnAjuda04)
        self.pushButton_BtnAjuda02 = QtWidgets.QPushButton(parent=self.frame_CentralAjuda)
        self.pushButton_BtnAjuda02.setMinimumSize(QtCore.QSize(0, 50))
        self.pushButton_BtnAjuda02.setMaximumSize(QtCore.QSize(16777215, 50))
        self.pushButton_BtnAjuda02.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton_BtnAjuda02.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.pushButton_BtnAjuda02.setStyleSheet("QPushButton{\n"
"    text-align:left;\n"
"    color:#585858;\n"
"\n"
"    font-size:20px;\n"
"    cursor: pointer;\n"
"\n"
"    background-color:transparent;\n"
"    border-radius:0px;\n"
"    border-bottom: 1px solid #acacbf;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color:#4b6272;\n"
"}")
        self.pushButton_BtnAjuda02.setIcon(icon)
        self.pushButton_BtnAjuda02.setIconSize(QtCore.QSize(150, 150))
        self.pushButton_BtnAjuda02.setObjectName("pushButton_BtnAjuda02")
        self.verticalLayout_20.addWidget(self.pushButton_BtnAjuda02)
        self.pushButton_BtnAjuda03 = QtWidgets.QPushButton(parent=self.frame_CentralAjuda)
        self.pushButton_BtnAjuda03.setMinimumSize(QtCore.QSize(0, 65))
        self.pushButton_BtnAjuda03.setMaximumSize(QtCore.QSize(16777215, 65))
        self.pushButton_BtnAjuda03.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton_BtnAjuda03.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.pushButton_BtnAjuda03.setStyleSheet("QPushButton{\n"
"    text-align:left;\n"
"    color:#585858;\n"
"\n"
"    font-size:20px;\n"
"    cursor: pointer;\n"
"\n"
"    background-color:transparent;\n"
"    border-radius:0px;\n"
"    border-bottom: 1px solid #acacbf;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color:#4b6272;\n"
"}")
        self.pushButton_BtnAjuda03.setIcon(icon)
        self.pushButton_BtnAjuda03.setIconSize(QtCore.QSize(150, 150))
        self.pushButton_BtnAjuda03.setObjectName("pushButton_BtnAjuda03")
        self.verticalLayout_20.addWidget(self.pushButton_BtnAjuda03)
        self.label_TitleAjudaLEO = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_TitleAjudaLEO.setGeometry(QtCore.QRect(870, 490, 231, 51))
        self.label_TitleAjudaLEO.setStyleSheet("QLabel{\n"
"\n"
"color:#010101;\n"
"border:0px;\n"
"font-size:30px;\n"
"font-weight: bold;\n"
"}")
        self.label_TitleAjudaLEO.setObjectName("label_TitleAjudaLEO")
        self.label_SubTitleAjudaLEO2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_SubTitleAjudaLEO2.setGeometry(QtCore.QRect(870, 530, 241, 41))
        self.label_SubTitleAjudaLEO2.setStyleSheet("\n"
"QLabel{\n"
"color:#010101;\n"
"border:0px;\n"
"font-size:19px;\n"
"}")
        self.label_SubTitleAjudaLEO2.setObjectName("label_SubTitleAjudaLEO2")
        self.frame_7 = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_7.setGeometry(QtCore.QRect(850, 90, 267, 72))
        self.frame_7.setMaximumSize(QtCore.QSize(16777215, 80))
        self.frame_7.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_7.setObjectName("frame_7")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_7)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.pushButton_BtnHistorico_2 = QtWidgets.QPushButton(parent=self.frame_7)
        self.pushButton_BtnHistorico_2.setMinimumSize(QtCore.QSize(0, 48))
        self.pushButton_BtnHistorico_2.setMaximumSize(QtCore.QSize(234, 48))
        self.pushButton_BtnHistorico_2.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton_BtnHistorico_2.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.pushButton_BtnHistorico_2.setStyleSheet("QPushButton{\n"
"    text-align:left;\n"
"    color:#fff;\n"
"    border:0px;\n"
"    border-radius:20px;\n"
"    font-size:15px;\n"
"    cursor: pointer;\n"
"    background-color:#538fff;\n"
"}\n"
"QPushButton:hover{\n"
"background-color:#3668ff;\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/img/path395.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_BtnHistorico_2.setIcon(icon1)
        self.pushButton_BtnHistorico_2.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_BtnHistorico_2.setObjectName("pushButton_BtnHistorico_2")
        self.gridLayout_4.addWidget(self.pushButton_BtnHistorico_2, 0, 2, 1, 1)
        self.label_Restituicao_2 = QtWidgets.QLabel(parent=self.frame_7)
        self.label_Restituicao_2.setMaximumSize(QtCore.QSize(90, 16777215))
        self.label_Restituicao_2.setStyleSheet("\n"
"QLabel{\n"
"color:#9cb2cd;\n"
"border:0px;\n"
"font-size:15px;\n"
"}")
        self.label_Restituicao_2.setObjectName("label_Restituicao_2")
        self.gridLayout_4.addWidget(self.label_Restituicao_2, 0, 0, 1, 1)
        self.label_TxtValorRestituicao_2 = QtWidgets.QLabel(parent=self.frame_7)
        self.label_TxtValorRestituicao_2.setStyleSheet("\n"
"QLabel{\n"
"color:#273142;\n"
"border:0px;\n"
"font-size:15px;\n"
"}")
        self.label_TxtValorRestituicao_2.setObjectName("label_TxtValorRestituicao_2")
        self.gridLayout_4.addWidget(self.label_TxtValorRestituicao_2, 0, 1, 1, 1)
        self.frame_ColumnLeft = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_ColumnLeft.setGeometry(QtCore.QRect(10, 80, 221, 701))
        self.frame_ColumnLeft.setMaximumSize(QtCore.QSize(225, 16777215))
        self.frame_ColumnLeft.setStyleSheet("")
        self.frame_ColumnLeft.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_ColumnLeft.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_ColumnLeft.setObjectName("frame_ColumnLeft")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_ColumnLeft)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_4 = QtWidgets.QFrame(parent=self.frame_ColumnLeft)
        self.frame_4.setMinimumSize(QtCore.QSize(0, 80))
        self.frame_4.setMaximumSize(QtCore.QSize(16777215, 80))
        self.frame_4.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.pushButton_BtnDeclarar = QtWidgets.QPushButton(parent=self.frame_4)
        self.pushButton_BtnDeclarar.setMinimumSize(QtCore.QSize(0, 50))
        self.pushButton_BtnDeclarar.setMaximumSize(QtCore.QSize(234, 50))
        self.pushButton_BtnDeclarar.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton_BtnDeclarar.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.pushButton_BtnDeclarar.setStyleSheet("QPushButton{\n"
"    text-align:left;\n"
"    color:#fff;\n"
"    border:0px;\n"
"    border-radius:25px;\n"
"    font-size:20px;\n"
"    cursor: pointer;\n"
"    background-color:#538fff;\n"
"}\n"
"QPushButton:hover{\n"
"background-color:#3668ff;\n"
"}\n"
"\n"
"\n"
"")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(".\\assets/img/FAB-1.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_BtnDeclarar.setIcon(icon2)
        self.pushButton_BtnDeclarar.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_BtnDeclarar.setObjectName("pushButton_BtnDeclarar")
        self.verticalLayout_7.addWidget(self.pushButton_BtnDeclarar)
        self.verticalLayout_4.addWidget(self.frame_4)
        self.frame_8 = QtWidgets.QFrame(parent=self.frame_ColumnLeft)
        self.frame_8.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_8)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.pushButton_BtnServico = QtWidgets.QPushButton(parent=self.frame_8)
        self.pushButton_BtnServico.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_BtnServico.setMaximumSize(QtCore.QSize(16777215, 30))
        self.pushButton_BtnServico.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton_BtnServico.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.pushButton_BtnServico.setStyleSheet("QPushButton{\n"
"    text-align:left;\n"
"    color:#77a6e7;\n"
"    border:0px;\n"
"    font-size:16px;\n"
"    cursor: pointer;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"text-decoration: underline;\n"
"font-weight: bold;\n"
"}\n"
"\n"
"")
        self.pushButton_BtnServico.setObjectName("pushButton_BtnServico")
        self.verticalLayout_6.addWidget(self.pushButton_BtnServico)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.verticalLayout_6.addItem(spacerItem)
        self.pushButton_BtnAssuntos = QtWidgets.QPushButton(parent=self.frame_8)
        self.pushButton_BtnAssuntos.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton_BtnAssuntos.setStyleSheet("QPushButton{\n"
"    text-align:left;\n"
"    color:#77a6e7;\n"
"    border:0px;\n"
"    font-size:16px;\n"
"    cursor: pointer;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"text-decoration: underline;\n"
"font-weight: bold;\n"
"}")
        self.pushButton_BtnAssuntos.setObjectName("pushButton_BtnAssuntos")
        self.verticalLayout_6.addWidget(self.pushButton_BtnAssuntos)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.verticalLayout_6.addItem(spacerItem1)
        self.pushButton_BtnAcessoInfo = QtWidgets.QPushButton(parent=self.frame_8)
        self.pushButton_BtnAcessoInfo.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton_BtnAcessoInfo.setStyleSheet("QPushButton{\n"
"    text-align:left;\n"
"    color:#77a6e7;\n"
"    border:0px;\n"
"    font-size:16px;\n"
"    cursor: pointer;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"text-decoration: underline;\n"
"font-weight: bold;\n"
"}")
        self.pushButton_BtnAcessoInfo.setObjectName("pushButton_BtnAcessoInfo")
        self.verticalLayout_6.addWidget(self.pushButton_BtnAcessoInfo)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.verticalLayout_6.addItem(spacerItem2)
        self.pushButton_BtnComposicao = QtWidgets.QPushButton(parent=self.frame_8)
        self.pushButton_BtnComposicao.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton_BtnComposicao.setStyleSheet("QPushButton{\n"
"    text-align:left;\n"
"    color:#77a6e7;\n"
"    border:0px;\n"
"    font-size:16px;\n"
"    cursor: pointer;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"text-decoration: underline;\n"
"font-weight: bold;\n"
"}")
        self.pushButton_BtnComposicao.setObjectName("pushButton_BtnComposicao")
        self.verticalLayout_6.addWidget(self.pushButton_BtnComposicao)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.verticalLayout_6.addItem(spacerItem3)
        self.pushButton_BtnConsultaProcessos = QtWidgets.QPushButton(parent=self.frame_8)
        self.pushButton_BtnConsultaProcessos.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton_BtnConsultaProcessos.setStyleSheet("QPushButton{\n"
"    text-align:left;\n"
"    color:#77a6e7;\n"
"    border:0px;\n"
"    font-size:16px;\n"
"    cursor: pointer;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"text-decoration: underline;\n"
"font-weight: bold;\n"
"}")
        self.pushButton_BtnConsultaProcessos.setObjectName("pushButton_BtnConsultaProcessos")
        self.verticalLayout_6.addWidget(self.pushButton_BtnConsultaProcessos)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.verticalLayout_6.addItem(spacerItem4)
        self.pushButton_BtnCentraisConteudo = QtWidgets.QPushButton(parent=self.frame_8)
        self.pushButton_BtnCentraisConteudo.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton_BtnCentraisConteudo.setStyleSheet("QPushButton{\n"
"    text-align:left;\n"
"    color:#77a6e7;\n"
"    border:0px;\n"
"    font-size:16px;\n"
"    cursor: pointer;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"text-decoration: underline;\n"
"font-weight: bold;\n"
"}")
        self.pushButton_BtnCentraisConteudo.setObjectName("pushButton_BtnCentraisConteudo")
        self.verticalLayout_6.addWidget(self.pushButton_BtnCentraisConteudo)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.verticalLayout_6.addItem(spacerItem5)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.verticalLayout_6.addItem(spacerItem6)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.verticalLayout_6.addItem(spacerItem7)
        self.pushButton_BtnGovbr = QtWidgets.QPushButton(parent=self.frame_8)
        self.pushButton_BtnGovbr.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton_BtnGovbr.setStyleSheet("QPushButton{\n"
"    text-align:left;\n"
"    color:#77a6e7;\n"
"    border:0px;\n"
"    font-size:16px;\n"
"    cursor: pointer;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"text-decoration: underline;\n"
"font-weight: bold;\n"
"}")
        self.pushButton_BtnGovbr.setObjectName("pushButton_BtnGovbr")
        self.verticalLayout_6.addWidget(self.pushButton_BtnGovbr)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_6.addItem(spacerItem8)
        self.pushButton_BtnConfiguracao = QtWidgets.QPushButton(parent=self.frame_8)
        self.pushButton_BtnConfiguracao.setStyleSheet("QPushButton{\n"
"    text-align:center;\n"
"    color:#acacbf;\n"
"    border:0px;\n"
"    font-size:16px;\n"
"    cursor: pointer;\n"
"    font-style: italic;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"text-decoration: underline;\n"
"}")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(".\\assets/img/setting.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_BtnConfiguracao.setIcon(icon3)
        self.pushButton_BtnConfiguracao.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_BtnConfiguracao.setObjectName("pushButton_BtnConfiguracao")
        self.verticalLayout_6.addWidget(self.pushButton_BtnConfiguracao)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.verticalLayout_6.addItem(spacerItem9)
        self.frame = QtWidgets.QFrame(parent=self.frame_8)
        self.frame.setMinimumSize(QtCore.QSize(0, 2))
        self.frame.setMaximumSize(QtCore.QSize(16777215, 2))
        self.frame.setStyleSheet("QFrame{\n"
"    background-color: #e9e9ee;\n"
"    border:0px;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_6.addWidget(self.frame)
        self.pushButton_BtnFeedback = QtWidgets.QPushButton(parent=self.frame_8)
        self.pushButton_BtnFeedback.setStyleSheet("QPushButton{\n"
"    text-align:center;\n"
"    color:#acacbf;\n"
"    border:0px;\n"
"    font-size:14px;\n"
"    cursor: pointer;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"text-decoration: underline;\n"
"}")
        self.pushButton_BtnFeedback.setObjectName("pushButton_BtnFeedback")
        self.verticalLayout_6.addWidget(self.pushButton_BtnFeedback)
        self.pushButton_BtnSugestao = QtWidgets.QPushButton(parent=self.frame_8)
        self.pushButton_BtnSugestao.setStyleSheet("QPushButton{\n"
"    text-align:center;\n"
"    color:#acacbf;\n"
"    border:0px;\n"
"    font-size:14px;\n"
"    cursor: pointer;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"text-decoration: underline;\n"
"}")
        self.pushButton_BtnSugestao.setObjectName("pushButton_BtnSugestao")
        self.verticalLayout_6.addWidget(self.pushButton_BtnSugestao)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.verticalLayout_6.addItem(spacerItem10)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.verticalLayout_6.addItem(spacerItem11)
        self.label_6 = QtWidgets.QLabel(parent=self.frame_8)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_6.addWidget(self.label_6)
        self.label_8 = QtWidgets.QLabel(parent=self.frame_8)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_6.addWidget(self.label_8)
        self.verticalLayout_4.addWidget(self.frame_8)
        self.frame_DashCentral = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_DashCentral.setGeometry(QtCore.QRect(230, 90, 621, 711))
        self.frame_DashCentral.setStyleSheet("QFrame{\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius:10px;\n"
"border:0px;\n"
"}")
        self.frame_DashCentral.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_DashCentral.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_DashCentral.setObjectName("frame_DashCentral")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_DashCentral)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.frame_11 = QtWidgets.QFrame(parent=self.frame_DashCentral)
        self.frame_11.setMinimumSize(QtCore.QSize(0, 250))
        self.frame_11.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_11.setObjectName("frame_11")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_11)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.frame_3 = QtWidgets.QFrame(parent=self.frame_11)
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.frame_CPF = QtWidgets.QFrame(parent=self.frame_3)
        self.frame_CPF.setGeometry(QtCore.QRect(0, -10, 441, 250))
        self.frame_CPF.setMinimumSize(QtCore.QSize(0, 250))
        self.frame_CPF.setMaximumSize(QtCore.QSize(16777215, 250))
        self.frame_CPF.setStyleSheet("QFrame{ \n"
"background-color: #f2f2f2;\n"
"\n"
"\n"
" }")
        self.frame_CPF.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_CPF.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_CPF.setObjectName("frame_CPF")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.frame_CPF)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.frame_19 = QtWidgets.QFrame(parent=self.frame_CPF)
        self.frame_19.setMinimumSize(QtCore.QSize(200, 0))
        self.frame_19.setStyleSheet("QFrame{ border:0px }")
        self.frame_19.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_19.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_19.setObjectName("frame_19")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.frame_19)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_TitleCPF_3 = QtWidgets.QLabel(parent=self.frame_19)
        self.label_TitleCPF_3.setStyleSheet("QLabel{\n"
"\n"
"color:#4b6272;\n"
"border:0px;\n"
"font-size:45px;\n"
"font-weight: bold;\n"
"}")
        self.label_TitleCPF_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_TitleCPF_3.setObjectName("label_TitleCPF_3")
        self.verticalLayout_12.addWidget(self.label_TitleCPF_3)
        spacerItem12 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_12.addItem(spacerItem12)
        self.button_RPS_3 = QtWidgets.QPushButton(parent=self.frame_19)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.button_RPS_3.sizePolicy().hasHeightForWidth())
        self.button_RPS_3.setSizePolicy(sizePolicy)
        self.button_RPS_3.setMinimumSize(QtCore.QSize(0, 50))
        self.button_RPS_3.setMaximumSize(QtCore.QSize(234, 50))
        self.button_RPS_3.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.button_RPS_3.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.button_RPS_3.setStyleSheet("QPushButton{\n"
"    text-align:left;\n"
"    color:#fff;\n"
"    border:0px;\n"
"    border-radius:25px;\n"
"    font-size:20px;\n"
"    cursor: pointer;\n"
"    background-color:#538fff;\n"
"}\n"
"QPushButton:hover{\n"
"background-color:#3668ff;\n"
"}\n"
"\n"
"\n"
"")
        self.button_RPS_3.setIcon(icon1)
        self.button_RPS_3.setIconSize(QtCore.QSize(40, 40))
        self.button_RPS_3.setObjectName("button_RPS_3")
        self.verticalLayout_12.addWidget(self.button_RPS_3)
        self.horizontalLayout_11.addWidget(self.frame_19)
        self.frame_20 = QtWidgets.QFrame(parent=self.frame_CPF)
        self.frame_20.setStyleSheet("QFrame{ border:0px }")
        self.frame_20.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_20.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_20.setObjectName("frame_20")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.frame_20)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_4 = QtWidgets.QLabel(parent=self.frame_20)
        self.label_4.setEnabled(True)
        self.label_4.setMaximumSize(QtCore.QSize(65535, 65535))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap(".\\../Project/images/rps1.jpg"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_13.addWidget(self.label_4)
        self.horizontalLayout_11.addWidget(self.frame_20)
        self.frame_23 = QtWidgets.QFrame(parent=self.frame_3)
        self.frame_23.setGeometry(QtCore.QRect(0, 240, 391, 171))
        self.frame_23.setStyleSheet("QFrame{ border:0px }")
        self.frame_23.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_23.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_23.setObjectName("frame_23")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.frame_23)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.frame_24 = QtWidgets.QFrame(parent=self.frame_23)
        self.frame_24.setStyleSheet("QFrame{ border:0px }")
        self.frame_24.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_24.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_24.setObjectName("frame_24")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.frame_24)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.frame_21 = QtWidgets.QFrame(parent=self.frame_24)
        self.frame_21.setMinimumSize(QtCore.QSize(200, 0))
        self.frame_21.setStyleSheet("QFrame{ border:0px }")
        self.frame_21.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_21.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_21.setObjectName("frame_21")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.frame_21)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_TitleAlfandega = QtWidgets.QLabel(parent=self.frame_21)
        self.label_TitleAlfandega.setMinimumSize(QtCore.QSize(230, 0))
        self.label_TitleAlfandega.setStyleSheet("QLabel{\n"
"\n"
"color:#4b6272;\n"
"border:0px;\n"
"font-size:45px;\n"
"font-weight: bold;\n"
"}")
        self.label_TitleAlfandega.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_TitleAlfandega.setObjectName("label_TitleAlfandega")
        self.verticalLayout_13.addWidget(self.label_TitleAlfandega)
        spacerItem13 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_13.addItem(spacerItem13)
        self.horizontalLayout_14.addWidget(self.frame_21)
        self.label_5 = QtWidgets.QLabel(parent=self.frame_24)
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap(".\\../Project/images/Dino.jpg"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_14.addWidget(self.label_5)
        self.verticalLayout_15.addWidget(self.frame_24)
        self.button_Dino = QtWidgets.QPushButton(parent=self.frame_23)
        self.button_Dino.setMinimumSize(QtCore.QSize(0, 50))
        self.button_Dino.setMaximumSize(QtCore.QSize(234, 50))
        self.button_Dino.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.button_Dino.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.button_Dino.setStyleSheet("QPushButton{\n"
"    text-align:left;\n"
"    color:#fff;\n"
"    border:0px;\n"
"    border-radius:25px;\n"
"    font-size:20px;\n"
"    cursor: pointer;\n"
"    background-color:#538fff;\n"
"}\n"
"QPushButton:hover{\n"
"background-color:#3668ff;\n"
"}\n"
"\n"
"\n"
"")
        self.button_Dino.setIcon(icon1)
        self.button_Dino.setIconSize(QtCore.QSize(40, 40))
        self.button_Dino.setObjectName("button_Dino")
        self.verticalLayout_15.addWidget(self.button_Dino)
        self.frame_AjusteAnual = QtWidgets.QFrame(parent=self.frame_3)
        self.frame_AjusteAnual.setGeometry(QtCore.QRect(-10, 410, 561, 250))
        self.frame_AjusteAnual.setMinimumSize(QtCore.QSize(0, 250))
        self.frame_AjusteAnual.setStyleSheet("QFrame{ background-color: #f2f2f2; }")
        self.frame_AjusteAnual.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_AjusteAnual.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_AjusteAnual.setObjectName("frame_AjusteAnual")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.frame_AjusteAnual)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.frame_22 = QtWidgets.QFrame(parent=self.frame_AjusteAnual)
        self.frame_22.setStyleSheet("QFrame{ border:0px }")
        self.frame_22.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_22.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_22.setObjectName("frame_22")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.frame_22)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_2 = QtWidgets.QLabel(parent=self.frame_22)
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(".\\../Project/images/minesweeper.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_16.addWidget(self.label_2)
        self.horizontalLayout_15.addWidget(self.frame_22)
        self.frame_26 = QtWidgets.QFrame(parent=self.frame_AjusteAnual)
        self.frame_26.setStyleSheet("QFrame{ border:0px }")
        self.frame_26.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_26.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_26.setObjectName("frame_26")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.frame_26)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        spacerItem14 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_14.addItem(spacerItem14)
        self.label_TitleDeclaracao = QtWidgets.QLabel(parent=self.frame_26)
        self.label_TitleDeclaracao.setStyleSheet("QLabel{\n"
"\n"
"color:#4b6272;\n"
"border:0px;\n"
"font-size:40px;\n"
"}")
        self.label_TitleDeclaracao.setObjectName("label_TitleDeclaracao")
        self.verticalLayout_14.addWidget(self.label_TitleDeclaracao)
        self.button_minesweeper = QtWidgets.QPushButton(parent=self.frame_26)
        self.button_minesweeper.setMinimumSize(QtCore.QSize(0, 50))
        self.button_minesweeper.setMaximumSize(QtCore.QSize(234, 50))
        self.button_minesweeper.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.button_minesweeper.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.button_minesweeper.setStyleSheet("QPushButton{\n"
"    text-align:left;\n"
"    color:#fff;\n"
"    border:0px;\n"
"    border-radius:25px;\n"
"    font-size:20px;\n"
"    cursor: pointer;\n"
"    background-color:#538fff;\n"
"}\n"
"QPushButton:hover{\n"
"background-color:#3668ff;\n"
"}\n"
"\n"
"\n"
"")
        self.button_minesweeper.setIcon(icon1)
        self.button_minesweeper.setIconSize(QtCore.QSize(40, 40))
        self.button_minesweeper.setObjectName("button_minesweeper")
        self.verticalLayout_14.addWidget(self.button_minesweeper)
        spacerItem15 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_14.addItem(spacerItem15)
        self.horizontalLayout_15.addWidget(self.frame_26)
        self.frame_27 = QtWidgets.QFrame(parent=self.frame_AjusteAnual)
        self.frame_27.setStyleSheet("QFrame{ border:0px }")
        self.frame_27.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_27.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_27.setObjectName("frame_27")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.frame_27)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.horizontalLayout_15.addWidget(self.frame_27)
        self.horizontalLayout_8.addWidget(self.frame_3)
        self.verticalLayout_8.addWidget(self.frame_11)
        self.frame_Top_2 = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_Top_2.setGeometry(QtCore.QRect(10, 10, 1101, 71))
        self.frame_Top_2.setMaximumSize(QtCore.QSize(16777215, 80))
        self.frame_Top_2.setStyleSheet("QFrame{\n"
"\n"
"    background-color: rgb(255, 255, 255);\n"
"    border:0px;\n"
"}")
        self.frame_Top_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_Top_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_Top_2.setObjectName("frame_Top_2")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_Top_2)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.frame_TopLeft_2 = QtWidgets.QFrame(parent=self.frame_Top_2)
        self.frame_TopLeft_2.setMinimumSize(QtCore.QSize(282, 0))
        self.frame_TopLeft_2.setMaximumSize(QtCore.QSize(282, 16777215))
        self.frame_TopLeft_2.setStyleSheet("QFrame{\n"
"border:0px;\n"
"\n"
"}")
        self.frame_TopLeft_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_TopLeft_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_TopLeft_2.setObjectName("frame_TopLeft_2")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.frame_TopLeft_2)
        self.verticalLayout_22.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_22.setSpacing(0)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.pushButton_LogoReceitaFederal_2 = QtWidgets.QPushButton(parent=self.frame_TopLeft_2)
        self.pushButton_LogoReceitaFederal_2.setMinimumSize(QtCore.QSize(50, 60))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_LogoReceitaFederal_2.setFont(font)
        self.pushButton_LogoReceitaFederal_2.setAutoFillBackground(False)
        self.pushButton_LogoReceitaFederal_2.setStyleSheet("QPushButton{\n"
"\n"
"color:#1f3b6f;\n"
"font-weight: bold;\n"
"background-color:transparent;\n"
"font-size:26px;\n"
"border:0px;\n"
"}")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(".\\assets/img/receita-federal 1-1.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_LogoReceitaFederal_2.setIcon(icon4)
        self.pushButton_LogoReceitaFederal_2.setIconSize(QtCore.QSize(200, 200))
        self.pushButton_LogoReceitaFederal_2.setObjectName("pushButton_LogoReceitaFederal_2")
        self.verticalLayout_22.addWidget(self.pushButton_LogoReceitaFederal_2)
        self.horizontalLayout_6.addWidget(self.frame_TopLeft_2)
        self.frame_TopCenter_2 = QtWidgets.QFrame(parent=self.frame_Top_2)
        self.frame_TopCenter_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_TopCenter_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_TopCenter_2.setObjectName("frame_TopCenter_2")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.frame_TopCenter_2)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.textEdit_TxtTopSearch_2 = QtWidgets.QTextEdit(parent=self.frame_TopCenter_2)
        self.textEdit_TxtTopSearch_2.setMinimumSize(QtCore.QSize(242, 0))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.textEdit_TxtTopSearch_2.setFont(font)
        self.textEdit_TxtTopSearch_2.setAcceptDrops(False)
        self.textEdit_TxtTopSearch_2.setToolTip("")
        self.textEdit_TxtTopSearch_2.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.textEdit_TxtTopSearch_2.setStyleSheet("QTextEdit{\n"
"border-radius:15px;\n"
"background-color: #f2f2f2;\n"
"text-align: center;\n"
"font-size:30px;\n"
"color:#8e8e8e;\n"
"}")
        self.textEdit_TxtTopSearch_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.textEdit_TxtTopSearch_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.textEdit_TxtTopSearch_2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.textEdit_TxtTopSearch_2.setReadOnly(False)
        self.textEdit_TxtTopSearch_2.setObjectName("textEdit_TxtTopSearch_2")
        self.horizontalLayout_12.addWidget(self.textEdit_TxtTopSearch_2)
        self.horizontalLayout_6.addWidget(self.frame_TopCenter_2)
        self.frame_TopRight_2 = QtWidgets.QFrame(parent=self.frame_Top_2)
        self.frame_TopRight_2.setMinimumSize(QtCore.QSize(350, 0))
        self.frame_TopRight_2.setMaximumSize(QtCore.QSize(350, 16777215))
        self.frame_TopRight_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_TopRight_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_TopRight_2.setObjectName("frame_TopRight_2")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.frame_TopRight_2)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.horizontalLayout_6.addWidget(self.frame_TopRight_2)
        self.frame_TopDataUser_2 = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_TopDataUser_2.setGeometry(QtCore.QRect(909, 15, 151, 71))
        self.frame_TopDataUser_2.setMinimumSize(QtCore.QSize(150, 0))
        self.frame_TopDataUser_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_TopDataUser_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_TopDataUser_2.setObjectName("frame_TopDataUser_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_TopDataUser_2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_TxtTopDataUser_3 = QtWidgets.QLabel(parent=self.frame_TopDataUser_2)
        self.label_TxtTopDataUser_3.setStyleSheet("QLabel{\n"
"\n"
"color:#273142;\n"
"\n"
"}")
        self.label_TxtTopDataUser_3.setObjectName("label_TxtTopDataUser_3")
        self.verticalLayout_5.addWidget(self.label_TxtTopDataUser_3)
        self.label_TxtTopDataUserType_3 = QtWidgets.QLabel(parent=self.frame_TopDataUser_2)
        self.label_TxtTopDataUserType_3.setMinimumSize(QtCore.QSize(0, 19))
        self.label_TxtTopDataUserType_3.setStyleSheet("QLabel{\n"
"color:#9cb2cd;\n"
"}")
        self.label_TxtTopDataUserType_3.setObjectName("label_TxtTopDataUserType_3")
        self.verticalLayout_5.addWidget(self.label_TxtTopDataUserType_3)
        self.textBrowser = QtWidgets.QTextBrowser(parent=self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(870, 600, 261, 171))
        self.textBrowser.setObjectName("textBrowser")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1140, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_TitleCentralAjuda.setText(_translate("MainWindow", "Reference"))
        self.pushButton_BtnAjuda01.setText(_translate("MainWindow", "    Instruction "))
        self.pushButton_BtnAjuda04.setText(_translate("MainWindow", "    Advertisement"))
        self.pushButton_BtnAjuda02.setText(_translate("MainWindow", "    Setting"))
        self.pushButton_BtnAjuda03.setText(_translate("MainWindow", "    Reviews"))
        self.label_TitleAjudaLEO.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; color:#55ff7f;\">See more details at</span></p></body></html>"))
        self.label_SubTitleAjudaLEO2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" color:#55ff7f;\">www.gamenet.koco.com</span></p></body></html>"))
        self.pushButton_BtnHistorico_2.setText(_translate("MainWindow", "    Introduction"))
        self.label_Restituicao_2.setText(_translate("MainWindow", "Card"))
        self.label_TxtValorRestituicao_2.setText(_translate("MainWindow", "$ 10.000"))
        self.pushButton_BtnDeclarar.setText(_translate("MainWindow", "       Acceess"))
        self.pushButton_BtnServico.setText(_translate("MainWindow", "Service"))
        self.pushButton_BtnAssuntos.setText(_translate("MainWindow", "Issue"))
        self.pushButton_BtnAcessoInfo.setText(_translate("MainWindow", "Access Information"))
        self.pushButton_BtnComposicao.setText(_translate("MainWindow", "Features"))
        self.pushButton_BtnConsultaProcessos.setText(_translate("MainWindow", "Block"))
        self.pushButton_BtnCentraisConteudo.setText(_translate("MainWindow", "News"))
        self.pushButton_BtnGovbr.setText(_translate("MainWindow", "     GAMENET.KOCO"))
        self.pushButton_BtnConfiguracao.setText(_translate("MainWindow", "configure"))
        self.pushButton_BtnFeedback.setText(_translate("MainWindow", "Feedback"))
        self.pushButton_BtnSugestao.setText(_translate("MainWindow", "Suggest"))
        self.label_6.setText(_translate("MainWindow", "          Sign in"))
        self.label_8.setText(_translate("MainWindow", "          Sign up"))
        self.label_TitleCPF_3.setText(_translate("MainWindow", "RPS"))
        self.button_RPS_3.setText(_translate("MainWindow", "           Play"))
        self.label_TitleAlfandega.setText(_translate("MainWindow", "DINO"))
        self.button_Dino.setText(_translate("MainWindow", "                Play"))
        self.label_TitleDeclaracao.setText(_translate("MainWindow", "MINESWEEPER"))
        self.button_minesweeper.setText(_translate("MainWindow", "                Play"))
        self.pushButton_LogoReceitaFederal_2.setText(_translate("MainWindow", "Home Page"))
        self.textEdit_TxtTopSearch_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:30px; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Noto Sans\'; font-size:14pt;\">Search</span></p></body></html>"))
        self.label_TxtTopDataUser_3.setText(_translate("MainWindow", "{USER}"))
        self.label_TxtTopDataUserType_3.setText(_translate("MainWindow", "{PROFILE_TYPE}"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; font-weight:600; font-style:italic;\">License</span></p>\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">These games are based off of established licenses</span></p>\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">Need to license mobile and web games for your business?</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">MarketJS allows you to license premium games instantly, customize according to your brand, and deploy to your own servers.</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">Our based games work 100% on mobile and desktop devices. We cover PCs, laptops, Windows, Mac, iPhone, iPods, iPads, Android devices, Windows Phones and more</span><br /></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())

