# Form implementation generated from reading ui file 'home.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1132, 617)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(300, 30, 181, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.rpsButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.rpsButton.setGeometry(QtCore.QRect(90, 440, 231, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.rpsButton.setFont(font)
        self.rpsButton.setObjectName("rpsButton")
        self.minesweeperButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.minesweeperButton.setGeometry(QtCore.QRect(450, 440, 231, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.minesweeperButton.setFont(font)
        self.minesweeperButton.setObjectName("minesweeperButton")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(400, 90, 311, 331))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("images/msper.jpg"))
        self.label_3.setObjectName("label_3")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(50, 100, 331, 311))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("images/rps2.jpg"))
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(770, 100, 331, 311))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("images/snake-game.png"))
        self.label_4.setObjectName("label_4")
        self.snakeButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.snakeButton.setGeometry(QtCore.QRect(800, 440, 231, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.snakeButton.setFont(font)
        self.snakeButton.setObjectName("snakeButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1132, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "TRÒ CHƠI"))
        self.rpsButton.setText(_translate("MainWindow", "PRS Game"))
        self.minesweeperButton.setText(_translate("MainWindow", "Minesweeper"))
        self.snakeButton.setText(_translate("MainWindow", "Snake Game"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
